openapi: 3.0.0
info:
  title: "BRK Wijzigingen API"
  version: "1.0.0"
  contact:
    name: test
    email: me@home.nl
    url: http://home.nl
paths:
  /wijzigingen:
    get:
      tags: 
      - wijzigingen
      operationId: getWijzigingen
      parameters:
        - name: gemeentecode
          in: query
          description: gemeenteCode
          required: true
          schema:
            type: string
        - name: van
          in: query
          description: "van"
          required: true
          schema:
            type: string
            format: date
        - name: tot
          in: query
          description: "tot"
          required: false
          schema:
            type: string
            format: date
      responses:
        200:
          description: "response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WijzigingenHal'
              examples:
                nieuwKoz:
                  $ref: '#/components/examples/NieuwKadastraalOnroerendeZaak'
                gewijzigdKoz:
                  $ref: '#/components/examples/GewijzigdKadastraalOnroerendeZaak'
                beeindigdKoz:
                  $ref: '#/components/examples/BeeindigdKadastraalOnroerendeZaak'
                samenvoegingKoz:
                  $ref: '#/components/examples/SamenvoegingKadastraalOnroerendeZaak'
                splitsingKoz:
                  $ref: '#/components/examples/SplitsingKadastraalOnroerendeZaak'
                nieuwZag:
                  $ref: '#/components/examples/NieuwZakelijkGerechtigde'
                gewijzigdZag:
                  $ref: '#/components/examples/GewijzigdZakelijkGerechtigde'
                beeindigdZag:
                  $ref: '#/components/examples/BeeindigdZakelijkGerechtigde'
                langerDanEenWeek:
                  $ref: '#/components/examples/BevraagPeriodeLangerDanEenWeek'
                alleenVan:
                  $ref: '#/components/examples/AlleenVanDatum'
        400:
          $ref: '#/components/responses/400'

components:
  responses:
    '400':
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/BadRequestFoutbericht'
          examples:
            alleenTotDatum:
              $ref: '#/components/examples/AlleenTotDatum'

  schemas:
    WijzigingenHal:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/WijzigingenHal_links'
        wijzigingen:
          $ref: '#/components/schemas/Wijzigingen'
    WijzigingenHal_links:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks'
        - properties:
            kadastraalonroerendezaak:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink'
            zakelijkGerechtigde:          
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink'
            vervolgbevragingen:
              type: array
              items:
                $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink'
    Wijzigingen:
      type: array
      items:
        $ref: '#/components/schemas/Wijziging'
    Wijziging:
      type: object
      properties:
        kadastraalobjectidentificatie:
          type: string
        zakelijkgerechtigdeidentificatie:
          type: string
        type:
          type: string
        mutatiedatum:
          type: string
          format: date
  examples:
    NieuwKadastraalOnroerendeZaak:
      summary: nieuw kadastraal onroerende zaak
      value:
        _links:
          self:
            href: 'wijzigingen?van=2020-02-01&tot=2020-02-02&gemeentecode=0344'
          kadastraalOnroerendeZaak:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-01'
    GewijzigdKadastraalOnroerendeZaak:
      summary: gewijzigd kadastraal onroerende zaak
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-03&tot=2020-02-04&gemeentecode=0344'
          kadastraalOnroerendeZaak:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-03'
    BeeindigdKadastraalOnroerendeZaak:
      summary: beëindigd kadastraal onroerende zaak
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-05&tot=2020-02-06&gemeentecode=0344'
          kadastraalOnroerendeZaak:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-05'
    SamenvoegingKadastraalOnroerendeZaak:
      summary: samenvoeging van meerdere kadastraal onroerende zaken
      description: kadastraal onroerende zaken met identificatie '56789012' en '67890123' worden samengevoegd tot '78901234'
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-06&tot=2020-02-07&gemeentecode=0344'
          kadastraalOnroerendeZaak:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-06'
          - kadastraalobjectidentificatie: 67890123
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-06'
          - kadastraalobjectidentificatie: 78901234
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-06'
    SplitsingKadastraalOnroerendeZaak:
      summary: splitsing van kadastraal onroerende zaak
      description: kadastraal onroerende zaak met identificatie '78901234' wordt gesplitst in kadastraal onroerende zaken met identificatie '89012345' en '90123456'
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-07&tot=2020-02-08&gemeentecode=0344'
          kadastraalOnroerendeZaak:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 78901234
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-07'
          - kadastraalobjectidentificatie: 89012345
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-07'
          - kadastraalobjectidentificatie: 90123456
            type: kadastraalonroerendezaak
            mutatiedatum: '2020-02-07'
    NieuwZakelijkGerechtigde:
      summary: nieuw zakelijk gerechtigde
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-10&tot=2020-02-11&gemeentecode=0344'
          zakelijkGerechtigde:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            zakelijkgerechtigdeidentificatie: 12345678
            type: zakelijkgerechtigde
            mutatiedatum: '2020-02-10'
    GewijzigdZakelijkGerechtigde:
      summary: gewijzigd zakelijk gerechtigde
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-11&tot=2020-02-12&gemeentecode=0344'
          zakelijkGerechtigde:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            zakelijkgerechtigdeidentificatie: 12345678
            type: zakelijkgerechtigde
            mutatiedatum: '2020-02-11'
    BeeindigdZakelijkGerechtigde:
      summary: beëindigd zakelijk gerechtigde
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-12&tot=2020-02-13&gemeentecode=0344'
          zakelijkGerechtigde:
            href: '/kadastraalonroerendezaken/{kadastraalobjectidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}?mutatiedatum={mutatiedatum}'
            templated: true
        wijzigingen:
          - kadastraalobjectidentificatie: 56789012
            zakelijkgerechtigdeidentificatie: 12345678
            type: zakelijkgerechtigde
            mutatiedatum: '2020-02-12'
    BevraagPeriodeLangerDanEenWeek:
      summary: bevraag periode is langer dan één BevraagPeriodeLangerDanEenWeek
      description: de vervolgbevragingen zijn links met een periode van 7 dagen binnen de bevraag periode
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-12&tot=2020-02-13&gemeentecode=0344'
          vervolgbevragingen:
            - href: /wijzigingen?van=2020-02-08&tot=2020-02-15&gemeentecode=0344
            - href: /wijzigingen?van=2020-02-15&tot=2020-02-22&gemeentecode=0344
            - href: /wijzigingen?van=2020-02-22&tot=2020-02-29&gemeentecode=0344
            - href: /wijzigingen?van=2020-02-29&tot=2020-03-01&gemeentecode=0344
    AlleenVanDatum:
      summary: alleen van datum is opgegeven
      description: de van datum in de vervolgbevraging is de opgegeven van datum + 7 dagen
      value:
        _links:
          self:
            href: '/wijzigingen?van=2020-02-01&gemeentecode=0344'
          vervolgbevragingen:
            - href: /wijzigingen?van=2020-02-08&gemeentecode=0344
    AlleenTotDatum:
      summary: alleen tot datum is opgegeven
      description: de van datum is een verplicht veld
      value:
        type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#/10.4.1 400 Bad Request
        title: van parameter moet worden opgegeven.
        status: 400
        detail: The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.
        instance: /wijzigingen?parameter=van
        code: paramsRequired
        invalid-params:
          - type: https://www.vng.nl/realisatie/api/validaties/integer
            name: van
            code: date
            reason: van datum is verplicht.
